---
- name: mongodb delegate primary replicas
  ansible.builtin.shell: /opt/mongodb/mongodb_primary_delegator.py

- name: give the replicas time to sync with each other
  pause:
    seconds: 10

- name: mongodb restart ex-primary replicas
  include_tasks: mongodb_restart_service.yml